ln -s $(pwd)/zshrc ~/.zshrc
ln -s $(pwd)/vimrc ~/.vimrc
ln -s $(pwd)/gitconfig ~/.gitconfig
ln -s $(pwd)/dircolors ~/.dircolors
ln -s $(pwd)/config/i3/config ~/.config/i3/config
ln -s $(pwd)/config/nvim/init.vim ~/.config/nvim/init.vim
ln -s $(pwd)/config/termite/config ~/.config/termite/config
ln -s $(pwd)/vim/after/syntax/python.vim ~/.vim/after/syntax/python.vim
ln -s $(pwd)/vim/ftplugin/python.vim ~/.vim/ftplugin/python.vim
